const DEPARTMENTS_DATA = [
    { name: "Ain", code: "01", region: "Auvergne-Rhône-Alpes" },
    { name: "Aisne", code: "02", region: "Hauts-de-France" },
    { name: "Allier", code: "03", region: "Auvergne-Rhône-Alpes" },
    { name: "Alpes-de-Haute-Provence", code: "04", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Hautes-Alpes", code: "05", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Alpes-Maritimes", code: "06", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Ardèche", code: "07", region: "Auvergne-Rhône-Alpes" },
    { name: "Ardennes", code: "08", region: "Grand Est" },
    { name: "Ariège", code: "09", region: "Occitanie" },
    { name: "Aube", code: "10", region: "Grand Est" },
    { name: "Aude", code: "11", region: "Occitanie" },
    { name: "Aveyron", code: "12", region: "Occitanie" },
    { name: "Bouches-du-Rhône", code: "13", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Calvados", code: "14", region: "Normandie" },
    { name: "Cantal", code: "15", region: "Auvergne-Rhône-Alpes" },
    { name: "Charente", code: "16", region: "Nouvelle-Aquitaine" },
    { name: "Charente-Maritime", code: "17", region: "Nouvelle-Aquitaine" },
    { name: "Cher", code: "18", region: "Centre-Val de Loire" },
    { name: "Corrèze", code: "19", region: "Nouvelle-Aquitaine" },
    { name: "Corse-du-Sud", code: "2A", region: "Corse" },
    { name: "Haute-Corse", code: "2B", region: "Corse" },
    { name: "Côte-d'Or", code: "21", region: "Bourgogne-Franche-Comté" },
    { name: "Côtes-d'Armor", code: "22", region: "Bretagne" },
    { name: "Creuse", code: "23", region: "Nouvelle-Aquitaine" },
    { name: "Dordogne", code: "24", region: "Nouvelle-Aquitaine" },
    { name: "Doubs", code: "25", region: "Bourgogne-Franche-Comté" },
    { name: "Drôme", code: "26", region: "Auvergne-Rhône-Alpes" },
    { name: "Eure", code: "27", region: "Normandie" },
    { name: "Eure-et-Loir", code: "28", region: "Centre-Val de Loire" },
    { name: "Finistère", code: "29", region: "Bretagne" },
    { name: "Gard", code: "30", region: "Occitanie" },
    { name: "Haute-Garonne", code: "31", region: "Occitanie" },
    { name: "Gers", code: "32", region: "Occitanie" },
    { name: "Gironde", code: "33", region: "Nouvelle-Aquitaine" },
    { name: "Hérault", code: "34", region: "Occitanie" },
    { name: "Ille-et-Vilaine", code: "35", region: "Bretagne" },
    { name: "Indre", code: "36", region: "Centre-Val de Loire" },
    { name: "Indre-et-Loire", code: "37", region: "Centre-Val de Loire" },
    { name: "Isère", code: "38", region: "Auvergne-Rhône-Alpes" },
    { name: "Jura", code: "39", region: "Bourgogne-Franche-Comté" },
    { name: "Landes", code: "40", region: "Nouvelle-Aquitaine" },
    { name: "Loir-et-Cher", code: "41", region: "Centre-Val de Loire" },
    { name: "Loire", code: "42", region: "Auvergne-Rhône-Alpes" },
    { name: "Haute-Loire", code: "43", region: "Auvergne-Rhône-Alpes" },
    { name: "Loire-Atlantique", code: "44", region: "Pays de la Loire" },
    { name: "Loiret", code: "45", region: "Centre-Val de Loire" },
    { name: "Lot", code: "46", region: "Occitanie" },
    { name: "Lot-et-Garonne", code: "47", region: "Nouvelle-Aquitaine" },
    { name: "Lozère", code: "48", region: "Occitanie" },
    { name: "Maine-et-Loire", code: "49", region: "Pays de la Loire" },
    { name: "Manche", code: "50", region: "Normandie" },
    { name: "Marne", code: "51", region: "Grand Est" },
    { name: "Haute-Marne", code: "52", region: "Grand Est" },
    { name: "Mayenne", code: "53", region: "Pays de la Loire" },
    { name: "Meurthe-et-Moselle", code: "54", region: "Grand Est" },
    { name: "Meuse", code: "55", region: "Grand Est" },
    { name: "Morbihan", code: "56", region: "Bretagne" },
    { name: "Moselle", code: "57", region: "Grand Est" },
    { name: "Nièvre", code: "58", region: "Bourgogne-Franche-Comté" },
    { name: "Nord", code: "59", region: "Hauts-de-France" },
    { name: "Oise", code: "60", region: "Hauts-de-France" },
    { name: "Orne", code: "61", region: "Normandie" },
    { name: "Pas-de-Calais", code: "62", region: "Hauts-de-France" },
    { name: "Puy-de-Dôme", code: "63", region: "Auvergne-Rhône-Alpes" },
    { name: "Pyrénées-Atlantiques", code: "64", region: "Nouvelle-Aquitaine" },
    { name: "Hautes-Pyrénées", code: "65", region: "Occitanie" },
    { name: "Pyrénées-Orientales", code: "66", region: "Occitanie" },
    { name: "Bas-Rhin", code: "67", region: "Grand Est" },
    { name: "Haut-Rhin", code: "68", region: "Grand Est" },
    { name: "Rhône", code: "69", region: "Auvergne-Rhône-Alpes" },
    { name: "Haute-Saône", code: "70", region: "Bourgogne-Franche-Comté" },
    { name: "Saône-et-Loire", code: "71", region: "Bourgogne-Franche-Comté" },
    { name: "Sarthe", code: "72", region: "Pays de la Loire" },
    { name: "Savoie", code: "73", region: "Auvergne-Rhône-Alpes" },
    { name: "Haute-Savoie", code: "74", region: "Auvergne-Rhône-Alpes" },
    { name: "Paris", code: "75", region: "Île-de-France" },
    { name: "Seine-Maritime", code: "76", region: "Normandie" },
    { name: "Seine-et-Marne", code: "77", region: "Île-de-France" },
    { name: "Yvelines", code: "78", region: "Île-de-France" },
    { name: "Deux-Sèvres", code: "79", region: "Nouvelle-Aquitaine" },
    { name: "Somme", code: "80", region: "Hauts-de-France" },
    { name: "Tarn", code: "81", region: "Occitanie" },
    { name: "Tarn-et-Garonne", code: "82", region: "Occitanie" },
    { name: "Var", code: "83", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Vaucluse", code: "84", region: "Provence-Alpes-Côte d'Azur" },
    { name: "Vendée", code: "85", region: "Pays de la Loire" },
    { name: "Vienne", code: "86", region: "Nouvelle-Aquitaine" },
    { name: "Haute-Vienne", code: "87", region: "Nouvelle-Aquitaine" },
    { name: "Vosges", code: "88", region: "Grand Est" },
    { name: "Yonne", code: "89", region: "Bourgogne-Franche-Comté" },
    { name: "Territoire de Belfort", code: "90", region: "Bourgogne-Franche-Comté" },
    { name: "Essonne", code: "91", region: "Île-de-France" },
    { name: "Hauts-de-Seine", code: "92", region: "Île-de-France" },
    { name: "Seine-Saint-Denis", code: "93", region: "Île-de-France" },
    { name: "Val-de-Marne", code: "94", region: "Île-de-France" },
    { name: "Val-d'Oise", code: "95", region: "Île-de-France" },
    { name: "Guadeloupe", code: "971", region: "Outre-mer" },
    { name: "Martinique", code: "972", region: "Outre-mer" },
    { name: "Guyane", code: "973", region: "Outre-mer" },
    { name: "La Réunion", code: "974", region: "Outre-mer" },
    { name: "Saint-Pierre-et-Miquelon", code: "975", region: "Outre-mer" },
    { name: "Mayotte", code: "976", region: "Outre-mer" },
    { name: "Saint-Barthélemy", code: "977", region: "Outre-mer" },
    { name: "Saint-Martin", code: "978", region: "Outre-mer" },
    { name: "Terres australes et antarctiques françaises", code: "984", region: "Outre-mer" },
    { name: "Wallis-et-Futuna", code: "986", region: "Outre-mer" },
    { name: "Polynésie française", code: "987", region: "Outre-mer" },
    { name: "Nouvelle Calédonie", code: "988", region: "Outre-mer" },
    { name: "Île de Clipperton ", code: "989", region: "Outre-mer" }
];

Object.freeze(DEPARTMENTS_DATA);